### ISSUE TITLE
[Lecteur de flux] Identifier les nouveaux demandeurs en utilisant uniquement TOPPERSENTDRODEVORSA dans les flux bénéficiaires

### ISSUE THREAD

**Issue by aminedhobb** [betagouv/analyse-flux-insertion#19]
## Contexte

Les flux bénéficiaires nous permettent d'identifier les nouveaux demandeurs RSA.
L'objectif est de mettre en place une page où les utilisateurs peuvent uploader leur flux bénéficiaire, et retourner une liste des noms, prénoms et numéros d'allocataire pour tous les nouveaux demandeurs.

Règles de gestion : https://docs.google.com/presentation/d/1--YZdC8wiBS5zhgdHBn1wM-jYdYO5MjWZbEwAJVj21s/edit#slide=id.gcd0400ad3b_0_21

## Attentes

- [x] Identifier et afficher une liste de tous les noms, prénoms et numéros d'allocataire des nouveaux demandeurs RSA lorsqu'un flux bénéficiaire est uploadé

**Comment by ClaireCasu** [comment]
Après réunion Cnaf du 19 avril: dans un premier temps, on utilise uniquement la variable TOPPERSENTDRODEVORSA du jour J. On a besoin uniquement du fichier Bénéficiaire quotidien du jour J.  On utilisera les autres balises dans un second temps, pour affiner l'analyse.
