### ISSUE TITLE
[Lecteur de flux] Ajouter un bouton pour obtenir les données de contacts du flux instruction en csv

### ISSUE THREAD

**Issue by ClaireCasu** [betagouv/analyse-flux-insertion#23]
Dans l'onglet **Lecteur de fichier « Instruction » de la CNAF**, rajouter un bouton **Exporter les données de contact** à côté du bouton "vider l'historique".

Ce bouton générerait un export d'un fichier .csv contenant 5 colonnes: matricule ,nom, prénom, mail, téléphone.

**Comment by ClaireCasu** [comment]
Après réunion Cnaf du 19 avril, on exporte 5 colonnes: NUMDEMRSA, NIR, nom, prénom, mail, téléphone. Si il y a plusieurs personnes dans la demande, on récupère uniquement les données de la personne pour laquelle ROLEPERS=DEM

**Comment by aminedhobb** [comment]
Après le meeting avec Ardennes et consultation avec @ClaireCasu , il a été décidé d'exporter les données de toutes les personnes associées à une demande. Elles auront dans les cases mail et téléphone les coordonnées du demandeur. On ajoutera une case précisant le role de la personne.
