### ISSUE TITLE
[Lecteur flux instruction] Mauvais formatage du fichier csv des contacts

### ISSUE THREAD

**Issue by qblanc** [betagouv/analyse-flux-insertion#40]
L'export en csv des données de contact n'est pas lu correctement par excel (qui a des chances d'être l'outil utilisé par les agents pour lire les fichiers csv)

**Comment by aminedhobb** [comment]
https://startups-detat.slack.com/archives/C01U2A4RQRL/p1619514532001200?thread_ts=1619513420.000300&cid=C01U2A4RQRL
