### ISSUE TITLE
[Lecteur flux instruction] Séparer le tableau de stats en 2 tableaux

### ISSUE THREAD

**Issue by qblanc** [betagouv/analyse-flux-insertion#41]
Le tableau de stats du lecteur de flux instruction dépasse la largeur de mon écran 13 pouces (1920*1080), et il y a beaucoup d'informations dedans.
Il pourrait être intéressant de le séparer en deux tableaux, comme pour le flux bénéficiaires, avec un tableau stats en premier, puis un tableau historique en dessous (par exemple).

**Comment by aminedhobb** [comment]
Il faudrait aussi faire apparaître le nombre de personnes en plus du nombre de dossier. Le comptage des DSP devrait se faire sur les personnes vu que les données socio-professionnelles sont au niveau de la balise personne. 
Il serait intéressant aussi de rendre plus lisible la séparation `nombre | pourcentage`.
