### ISSUE TITLE
[Drôme] Rendre RDV non annulable dans RDV-Solidarités

### ISSUE THREAD

**Issue by aminedhobb** [betagouv/analyse-flux-insertion#89]
Une fois le RDV pris, le RDV ne doit pas être annulable sur RDV-Solidarités (convocation). Si ce n'est pas trop compliqué le rendre annulable une fois.

**Comment by qblanc** [comment]
La feature n'a (volontairement) pas été totalement résolue : pour répondre à cette issue, nous avons opté pour l'instant, en accord avec l'équipe de RDV-Solidarités, de ne pas autoriser les rendez-vous non annulables mais d'implémenter plutôt des messages d'avertissement personnalisables pour prévenir les usages des éventuelles conséquences d'une annulation.
Un point ultérieur sera fait une fois cette solution proposée aux départements.
